# Generated by Django 4.0.5 on 2022-06-17 02:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin1_us',
            fields=[
                ('ogc_find', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('iso3166_1_alpha_3', models.CharField(max_length=10)),
                ('statecode', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=20)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
