# Generated by Django 4.0.5 on 2022-06-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_admin1_us_delete_worldborder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1_us',
            old_name='wkb_geometry',
            new_name='wkb',
        ),
    ]
