# Generated by Django 4.0.5 on 2022-06-17 02:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_rename_admin1_us_admin1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1Us',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('iso3166_1_alpha_3', models.CharField(blank=True, max_length=10, null=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('id', models.CharField(blank=True, max_length=15, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'admin1_us',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='admin1',
        ),
    ]
